### Reescrever snapshot hdf5

Apagar partículas de gás

In [1]:
import h5py
import numpy as np

In [2]:
#snapshot a ser copiado
file = h5py.File('snapshot_000.hdf5', 'r+')
file.keys()

<KeysViewHDF5 ['Config', 'Header', 'Parameters', 'PartType0', 'PartType1', 'PartType2', 'PartType3', 'PartType4', 'PartType5']>

In [3]:
#ver número de cada tipo de patícula
print(file['Header'].attrs['NumPart_ThisFile'])
print(file['Header'].attrs['NumPart_Total'])

[  30715 1000000  160000   40000  169285    6500]
[  30715 1000000  160000   40000  169285    6500]


In [4]:
#alterar número e substituir
#reescreve o original!
numpart_file = np.array([0, 1000000, 160000, 40000, 169285, 6500], dtype=np.uint64)
file['Header'].attrs['NumPart_ThisFile'] = numpart_file 
file['Header'].attrs['NumPart_Total'] = numpart_file 

In [5]:
#verificação
print(file['Header'].attrs['NumPart_ThisFile'])
print(file['Header'].attrs['NumPart_Total'])

[      0 1000000  160000   40000  169285    6500]
[      0 1000000  160000   40000  169285    6500]


In [6]:
#escrever novo arquivo
file2 = h5py.File('teste2.hdf5', 'w')

In [7]:
#copiar grupos que farão parte do novo arquivo, ignorando os que não serã necessários
file.copy('Config', file2)
file.copy('Header', file2)
file.copy('Parameters', file2)
file.copy('PartType1', file2)
file.copy('PartType2', file2)
file.copy('PartType3', file2)
file.copy('PartType4', file2)
file.copy('PartType5', file2)

In [8]:
#verificação
print(file2.keys())
print(file2['PartType2'].keys())

<KeysViewHDF5 ['Config', 'Header', 'Parameters', 'PartType1', 'PartType2', 'PartType3', 'PartType4', 'PartType5']>
<KeysViewHDF5 ['Coordinates', 'Masses', 'Metallicity', 'ParticleIDs', 'StellarFormationTime', 'Velocities']>


In [9]:
file.close()

In [10]:
file2.close()